In [1]:
# memanggil dataset iris
from sklearn.datasets import load_iris
iris_ku = load_iris()

In [2]:
# simpan data fitur/kolom (X) dan target (y)
X = iris_ku.data
y = iris_ku.target

In [3]:
# Simpan nama fitur/kolom (X) dan target (y)
feature_names = iris_ku.feature_names
target_names = iris_ku.target_names

In [4]:
# tampil nama fitur dan target dataset
print("Feature names:", feature_names)
print("Target names:", target_names)

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [5]:
# X dan y adalah numpy arrays
print("\nType of X is:", type(X))


Type of X is: <class 'numpy.ndarray'>


In [6]:
# tampilkan 5 baris pertama
print("\nFirst 5 rows of X: \n", X[:5])


First 5 rows of X: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [7]:
# fitur (X) and target (y)
X = iris_ku.data
y = iris_ku.target

In [8]:
# splitting X dan y untuk data latih dan uji
from sklearn.model_selection import train_test_split
X_latih, X_tes, y_latih, y_tes = train_test_split(X, y, test_size=0.3, random_state=1)

In [9]:
# tampilkan data fitur latih dan uji
print (X_latih.shape)
print (X_tes.shape)

(105, 4)
(45, 4)


In [10]:
# tampilkan data target latih dan uji
print (y_latih.shape)
print (y_tes.shape)

(105,)
(45,)


In [11]:
# pelatihan pada data latih menggunakan KNN (k=3)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3, metric='minkowski')
knn.fit(X_latih, y_latih)

KNeighborsClassifier(n_neighbors=3)

In [12]:
# melakukan prediksi pada data uji
y_prediksi = knn.predict(X_tes)

In [13]:
# perbandingan nilai aktual (y_tes) dengan nilai prediksi (y _prediksi)
from sklearn import metrics
print ("Akurasi model kNN:", metrics.accuracy_score(y_tes, y_prediksi))

Akurasi model kNN: 0.9777777777777777


In [14]:
# prediksi menggunakan data sampel dibuat sendiri
contoh = [[3, 5, 4, 2], [2, 3, 5, 4]]
preds = knn.predict (contoh)
pred_species = [iris_ku.target_names[p] for p in preds]
print ("Prediksi :", pred_species)

Prediksi : ['versicolor', 'virginica']
